require("SomeArgentineCat.remap")
require("SomeArgentineCat.set")
require("SomeArgentineCat.ui")
require("SomeArgentineCat.semi-colon-add")
require("mason").setup()
vim.api.nvim_exec('language en_US', true)
